const SELECT_SKILLS_SECTION = 'SELECT_SKILLS_SECTION',
  SELECT_EDUCATION_SECTION = 'SELECT_EDUCATION_SECTION',
  SELECT_WORK_SECTION = 'SELECT_WORK_SECTION',
  SELECT_PORTFOLIO_SECTION = 'SELECT_PORTFOLIO_SECTION'

export {
  SELECT_SKILLS_SECTION,
  SELECT_EDUCATION_SECTION,
  SELECT_WORK_SECTION,
  SELECT_PORTFOLIO_SECTION
}
